export enum DocumentType {
	TRADE_LICENSE = 'TRADE_LICENSE',
	EMIRATES_ID = 'EMIRATES_ID',
	PASSPORT = 'PASSPORT',
	MOA = 'MEMORANDUM_OF_ASSOCIATION',
	SHARE_CERTIFICATE = 'SHARE_CERTIFICATE',
	BANK_STATEMENT = 'BANK_STATEMENT',
	LEASE_AGREEMENT = 'LEASE_AGREEMENT',
	AUDITED_FINANCIALS = 'AUDITED_FINANCIALS',
	BUSINESS_PROFILE = 'BUSINESS_PROFILE',
	VISA = 'VISA'
}

export enum DocumentStatus {
	VERIFIED = 'VERIFIED',
	PENDING = 'PENDING',
	REJECTED = 'REJECTED'
}
