const CORE_TYPES = {
	CONFIG: Symbol.for('CONFIG'),
	DB: Symbol.for('DB'),
	LOGGER: Symbol.for('LOGGER'),
	ERROR_HANDLER: Symbol.for('ERROR_HANDLER')
};

const USER_TYPES = {
	USER_SERVICE: Symbol.for('USER_SERVICE'),
	USER_CONTROLLER: Symbol.for('USER_CONTROLLER'),
	USER_MODEL: Symbol.for('USER_MODEL'),
	USER_REPOSITORY: Symbol.for('USER_REPOSITORY')
};

const BUSINESS_TYPES = {
	BUSINESS_SERVICE: Symbol.for('BUSINESS_SERVICE'),
	BUSINESS_CONTROLLER: Symbol.for('BUSINESS_CONTROLLER'),
	BUSINESS_MODEL: Symbol.for('BUSINESS_MODEL'),
	BUSINESS_REPOSITORY: Symbol.for('BUSINESS_REPOSITORY')
};

const BUSINESS_ADDRESS_TYPES = {
	BUSINESS_ADDRESS_SERVICE: Symbol.for('BUSINESS_ADDRESS_SERVICE'),
	BUSINESS_ADDRESS_CONTROLLER: Symbol.for('BUSINESS_ADDRESS_CONTROLLER'),
	BUSINESS_ADDRESS_MODEL: Symbol.for('BUSINESS_ADDRESS_MODEL'),
	BUSINESS_ADDRESS_REPOSITORY: Symbol.for('BUSINESS_ADDRESS_REPOSITORY')
};

const OWNERSHIP_TYPES = {
	OWNERSHIP_SERVICE: Symbol.for('OWNERSHIP_SERVICE'),
	OWNERSHIP_CONTROLLER: Symbol.for('OWNERSHIP_CONTROLLER'),
	OWNERSHIP_MODEL: Symbol.for('OWNERSHIP_MODEL'),
	OWNERSHIP_REPOSITORY: Symbol.for('OWNERSHIP_REPOSITORY')
};

const FINANCIAL_TYPES = {
	FINANCIAL_SERVICE: Symbol.for('FINANCIAL_SERVICE'),
	FINANCIAL_CONTROLLER: Symbol.for('FINANCIAL_CONTROLLER'),
	FINANCIAL_MODEL: Symbol.for('FINANCIAL_MODEL'),
	FINANCIAL_REPOSITORY: Symbol.for('FINANCIAL_REPOSITORY')
};

const OTHER_TYPES = {
	OTHER_SERVICE: Symbol.for('OTHER_SERVICE'),
	OTHER_CONTROLLER: Symbol.for('OTHER_CONTROLLER'),
	OTHER_MODEL: Symbol.for('OTHER_MODEL'),
	OTHER_REPOSITORY: Symbol.for('OTHER_REPOSITORY')
};

const SIGNATORY_TYPES = {
	SIGNATORY_CONTROLLER: Symbol.for('SIGNATORY_CONTROLLER')
};

const AI_TYPES = {
	HTTP_AI: Symbol.for('HTTP_AI')
};

const REDIS_TYPES = {
	REDIS_SERVICE: Symbol.for('REDIS_SERVICE')
};

const TYPES = {
	...CORE_TYPES,
	...USER_TYPES,
	...BUSINESS_TYPES,
	...BUSINESS_ADDRESS_TYPES,
	...OWNERSHIP_TYPES,
	...FINANCIAL_TYPES,
	...OTHER_TYPES,
	...SIGNATORY_TYPES,
	...AI_TYPES,
	...REDIS_TYPES
};

export default TYPES;
