const CORE_TYPES = {
	CONFIG: Symbol.for('CONFIG'),
	DB: Symbol.for('DB'),
	LOGGER: Symbol.for('LOGGER'),
	ERROR_HANDLER: Symbol.for('ERROR_HANDLER')
};

const USER_TYPES = {
	USER_SERVICE: Symbol.for('USER_SERVICE'),
	USER_CONTROLLER: Symbol.for('USER_CONTROLLER'),
	USER_MODEL: Symbol.for('USER_MODEL'),
	USER_REPOSITORY: Symbol.for('USER_REPOSITORY')
};

const BUSINESS_TYPES = {
	BUSINESS_SERVICE: Symbol.for('BUSINESS_SERVICE'),
	BUSINESS_CONTROLLER: Symbol.for('BUSINESS_CONTROLLER'),
	BUSINESS_MODEL: Symbol.for('BUSINESS_MODEL'),
	BUSINESS_REPOSITORY: Symbol.for('BUSINESS_REPOSITORY')
};

const BUSINESS_ADDRESS_TYPES = {
	BUSINESS_ADDRESS_SERVICE: Symbol.for('BUSINESS_ADDRESS_SERVICE'),
	BUSINESS_ADDRESS_CONTROLLER: Symbol.for('BUSINESS_ADDRESS_CONTROLLER'),
	BUSINESS_ADDRESS_MODEL: Symbol.for('BUSINESS_ADDRESS_MODEL'),
	BUSINESS_ADDRESS_REPOSITORY: Symbol.for('BUSINESS_ADDRESS_REPOSITORY')
};

const TYPES = {
	...CORE_TYPES,
	...USER_TYPES,
	...BUSINESS_TYPES,
	...BUSINESS_ADDRESS_TYPES
};

export default TYPES;
